name: 🚀 Release

on:
  workflow_dispatch:

env:
  NAME: 'dot-env-generator'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Checkout current pull-request revision code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟢 Configure Bun on runner
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        
      - name: 🔵 Install Task
        uses: arduino/setup-task@v2
  
      - name: 💼 Configure Git user
        run: |
          git config user.name "gbh-devops-bot"
          git config user.email "devops@gbh.com.do"

      - name: 📦 Install package dependencies using lockfile
        run: bun install --frozen-lockfile

      - name: 🔨 Run build
        run: bun run build

      - name: 🔨 Compile binary for supported platforms
        run: task build-and-compress

      - name: 🚀 Run new version for production
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_USER_TOKEN }}
