name: 🚀 Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    services:
       bun:
        image: oven/bun:alpine
        options: > 
          --volume /home/runner/work/${{ github.repository }}:/workspace
          --workdir /workspace

    steps:
      - name: 💻 Checkout current pull-request revision code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEVOPS_USER_TOKEN }}

      - name: 🟢 Configure Bun on runner
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        
      # - name: 🔵 Install Task
      #   uses: arduino/setup-task@v2
  
      - name: 💼 Configure Git user
        run: |
          git config user.name "gbh-devops-bot"
          git config user.email "devops@gbh.com.do"

      - name: 📦 Install package dependencies using lockfile
        run: bun install --frozen-lockfile
      - name: 📦 Install package dependencies using lockfile
        run: docker exec
            -t bun
            bun install -g @go-task/cli
            bun install --frozen-lockfile

      - name: 🔨 Run build
        run: docker exec
          -t bun 
          bun run build

      - name: 🔨 Compile binary for supported platforms
        run: docker exec
          -t bun
          task compile
          task compress
   
          
      - name: 🔨 Compile binary for supported platforms
        run: docker exec
          -t bun
          cp -r
          /workspace/dist
          ./dist

      - name: 🚀 Release a new version
        run: bun release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_USER_TOKEN }}
